### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by marc-gist** [porrey/Particle.GPS#1]
I'm not able to get this to build in the web build interface... keeps saying it can't find the header file!

Thanks,

**Comment by porrey** [comment]
Looks likes I left off the library path in the latest upload. This is from testing on other hardware. I will upload a new version fully tested using the new Particle library manager.

**Comment by porrey** [comment]
The library has been updated to the new v2 format and the header files references updated. Please verify. Note that the library was renamed to **Particle-GPS** as required by the new Particle library manager. The latest version is now **1.0.3**.
